# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import patient_pb2 as patient__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in patient_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PatientProtoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPatientById = channel.unary_unary(
                '/patient.PatientProto/GetPatientById',
                request_serializer=patient__pb2.GetPatientByIdRequest.SerializeToString,
                response_deserializer=patient__pb2.GetPatientByIdResponse.FromString,
                _registered_method=True)
        self.GetAllPatients = channel.unary_unary(
                '/patient.PatientProto/GetAllPatients',
                request_serializer=patient__pb2.Empty.SerializeToString,
                response_deserializer=patient__pb2.GetAllPatientsResponse.FromString,
                _registered_method=True)
        self.AddPatient = channel.unary_unary(
                '/patient.PatientProto/AddPatient',
                request_serializer=patient__pb2.AddPatientRequest.SerializeToString,
                response_deserializer=patient__pb2.AddPatientResponse.FromString,
                _registered_method=True)
        self.UpdatePatient = channel.unary_unary(
                '/patient.PatientProto/UpdatePatient',
                request_serializer=patient__pb2.UpdatePatientRequest.SerializeToString,
                response_deserializer=patient__pb2.UpdatePatientResponse.FromString,
                _registered_method=True)
        self.DeletePatient = channel.unary_unary(
                '/patient.PatientProto/DeletePatient',
                request_serializer=patient__pb2.DeletePatientRequest.SerializeToString,
                response_deserializer=patient__pb2.DeletePatientResponse.FromString,
                _registered_method=True)
        self.GetPatientRendezVous = channel.unary_unary(
                '/patient.PatientProto/GetPatientRendezVous',
                request_serializer=patient__pb2.GetPatientRendezVousRequest.SerializeToString,
                response_deserializer=patient__pb2.GetPatientRendezVousResponse.FromString,
                _registered_method=True)


class PatientProtoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPatientById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllPatients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientRendezVous(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientProtoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPatientById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientById,
                    request_deserializer=patient__pb2.GetPatientByIdRequest.FromString,
                    response_serializer=patient__pb2.GetPatientByIdResponse.SerializeToString,
            ),
            'GetAllPatients': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPatients,
                    request_deserializer=patient__pb2.Empty.FromString,
                    response_serializer=patient__pb2.GetAllPatientsResponse.SerializeToString,
            ),
            'AddPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPatient,
                    request_deserializer=patient__pb2.AddPatientRequest.FromString,
                    response_serializer=patient__pb2.AddPatientResponse.SerializeToString,
            ),
            'UpdatePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePatient,
                    request_deserializer=patient__pb2.UpdatePatientRequest.FromString,
                    response_serializer=patient__pb2.UpdatePatientResponse.SerializeToString,
            ),
            'DeletePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePatient,
                    request_deserializer=patient__pb2.DeletePatientRequest.FromString,
                    response_serializer=patient__pb2.DeletePatientResponse.SerializeToString,
            ),
            'GetPatientRendezVous': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientRendezVous,
                    request_deserializer=patient__pb2.GetPatientRendezVousRequest.FromString,
                    response_serializer=patient__pb2.GetPatientRendezVousResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'patient.PatientProto', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('patient.PatientProto', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientProto(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPatientById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientProto/GetPatientById',
            patient__pb2.GetPatientByIdRequest.SerializeToString,
            patient__pb2.GetPatientByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllPatients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientProto/GetAllPatients',
            patient__pb2.Empty.SerializeToString,
            patient__pb2.GetAllPatientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientProto/AddPatient',
            patient__pb2.AddPatientRequest.SerializeToString,
            patient__pb2.AddPatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientProto/UpdatePatient',
            patient__pb2.UpdatePatientRequest.SerializeToString,
            patient__pb2.UpdatePatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientProto/DeletePatient',
            patient__pb2.DeletePatientRequest.SerializeToString,
            patient__pb2.DeletePatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatientRendezVous(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientProto/GetPatientRendezVous',
            patient__pb2.GetPatientRendezVousRequest.SerializeToString,
            patient__pb2.GetPatientRendezVousResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
